services:
  smartmeeting:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartmeeting-app
    network_mode: host
    environment:
      - STREAMLIT_SERVER_PORT=8729
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8729/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
