services:
  smartmeeting:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartmeeting-app
    ports:
      - "8899:8000"
    environment:
      - STREAMLIT_SERVER_PORT=8000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount exports directory for charts and exports
      - ./exports:/app/exports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
