version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Backend service (uncomment when backend is ready)
  # backend:
  #   image: smart-meeting-backend:latest
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://user:password@db:5432/smart_meeting
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  # Optional: Database service (uncomment when needed)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=smart_meeting
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: 